<a href="https://colab.research.google.com/github/tibalesut/test_2/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch

## Reshaping, stacking, queezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other, V or H stack
* Squeeze - whch removes all '1' dimensions from a tensor
* Unsqueeze -add a '1' diminesion to a traget tensor
* Permute - return a view of the imput with dimensions permuted (swapped) in a certain way.


In [5]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [6]:
# Add an extra dimension, reshape has to be compatible with the original size
# x_reshaped = x.reshape(1, 7)  # invalid because squeeze 9 element into 7
# x_reshaped = x.reshape(2, 9)  # invalid because because 2 times 9 is 18, we trying to double the number of elements
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [7]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [8]:
# change the view
z = x.view(1, 9)  # shares the memory of the original tensor
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [9]:
# Changing z changes x (a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [10]:
# stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape  # stacks verticaly

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [11]:
# stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape  # stacks horizontaly

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [12]:
# torch.squeeze) - remove all single dimensions from a traget sensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [13]:
x_reshaped.shape

torch.Size([1, 9])

In [14]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
x_reshaped.squeeze().shape  # 9

torch.Size([9])

In [16]:
x_squeezed = x_reshaped.squeeze()

In [17]:
# torch.unqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unqueezed}")
print(f"New tensor shape: {x_unqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New tensor shape: torch.Size([1, 9])


In [18]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
x = torch.rand(2, 3, 5)  # two items with 3 rows and 5 columns
x.size()

torch.Size([2, 3, 5])

In [19]:
x

tensor([[[0.7843, 0.9412, 0.4005, 0.9295, 0.8085],
         [0.1132, 0.5702, 0.9683, 0.1731, 0.1961],
         [0.9818, 0.3825, 0.5348, 0.5173, 0.5486]],

        [[0.4139, 0.8330, 0.3702, 0.4370, 0.4358],
         [0.6797, 0.7404, 0.8001, 0.8361, 0.6210],
         [0.0085, 0.4484, 0.9163, 0.1090, 0.7910]]])

In [24]:
torch.permute(x, (2, 0, 1)).size()  # reverses the shape

torch.Size([5, 2, 3])

In [30]:
y = torch.permute(x, (2, 0, 1))  # 5 items with 3 columns and two rows

In [31]:
y

tensor([[[0.7843, 0.1132, 0.9818],
         [0.4139, 0.6797, 0.0085]],

        [[0.9412, 0.5702, 0.3825],
         [0.8330, 0.7404, 0.4484]],

        [[0.4005, 0.9683, 0.5348],
         [0.3702, 0.8001, 0.9163]],

        [[0.9295, 0.1731, 0.5173],
         [0.4370, 0.8361, 0.1090]],

        [[0.8085, 0.1961, 0.5486],
         [0.4358, 0.6210, 0.7910]]])

In [33]:
# permute works with images (is a view)
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]

# Permute the original tensor to rearange the axis (or dim) order
# rearrange sothe color channels are the first dimension {color channels, height, width]

x_permuted = x_original.permute(2, 0, 1) # rearanges the dim, those are the arguments
# shifts axis 0-> 1, 1 -> 2, 2 -> 0
print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")  # items, columns,rows (n by m) is rows, columns in math

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [34]:
x_permuted

tensor([[[0.7901, 0.4577, 0.6941,  ..., 0.7999, 0.5791, 0.9623],
         [0.5891, 0.0187, 0.8582,  ..., 0.9724, 0.3302, 0.2796],
         [0.7690, 0.3082, 0.4854,  ..., 0.4823, 0.4991, 0.6693],
         ...,
         [0.2126, 0.8303, 0.8626,  ..., 0.3252, 0.5814, 0.1375],
         [0.1014, 0.2309, 0.7725,  ..., 0.8143, 0.0310, 0.4383],
         [0.1124, 0.4552, 0.2820,  ..., 0.9294, 0.6917, 0.9826]],

        [[0.1862, 0.9331, 0.8129,  ..., 0.1775, 0.7915, 0.8737],
         [0.2850, 0.7594, 0.2811,  ..., 0.8469, 0.6922, 0.2751],
         [0.0131, 0.7044, 0.6014,  ..., 0.8677, 0.3876, 0.0856],
         ...,
         [0.5778, 0.7835, 0.9141,  ..., 0.3719, 0.3910, 0.6670],
         [0.9487, 0.6082, 0.6187,  ..., 0.3741, 0.3181, 0.5052],
         [0.2544, 0.1610, 0.7352,  ..., 0.6313, 0.5871, 0.7797]],

        [[0.1271, 0.1193, 0.2388,  ..., 0.1161, 0.8497, 0.3819],
         [0.3468, 0.8135, 0.2290,  ..., 0.2124, 0.7016, 0.7077],
         [0.8937, 0.2884, 0.4305,  ..., 0.5045, 0.3766, 0.

## Indexing (selecting data from tensors with indexing)
Indexing with PyTorch is similar to indexing with NumPy


In [36]:
# cretae a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)  # 1 * 3 * 3 = 9
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [39]:
# let' index on new tensor, dim=0 is all
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [40]:
# index on middle bracket (dim=1)
x[0][1]


tensor([4, 5, 6])

In [41]:
# index on the most inner bracket
x[0][0][0]

tensor(1)

In [47]:
# get number 9
x[0][2][2]


tensor(9)

In [48]:
# you can use also use ":" to select all of a target dimension
x[:, 0]  # get all of the zero dimension and the all of the first item

tensor([[1, 2, 3]])

In [49]:
# get all values of the zero and first dimension but only index 1 of the second dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [50]:
# get all values of the zero dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [51]:
# get index 0 of 0th and 1st dimension and all values of second dimension
x[0, 0, :]

tensor([1, 2, 3])

In [57]:
# Index to return 9
print(x[:, 2, 2])
# index to return 3,6,9
print(x[:,:, 2])  # this is chained -> select all, get all of the inner items, select second column only

tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

NumPy is a popular scientific python (included in PyTorch) numericalcomputing library

Add because of this PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> 'torch.form_numpy(ndarray)'
* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()'

In [62]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)  # default data type is float64
tensor = torch.from_numpy(array).type(torch.float32)  # change from float64 to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [63]:
array.dtype

dtype('float64')

In [65]:
tensor.dtype

torch.float32

In [64]:
torch.arange(1.0, 8.0).dtype  # default data type in float32

torch.float32

In [67]:
# changethe value of array
array = array + 1  # add 1 to everyvalue in the array
array

array([3., 4., 5., 6., 7., 8., 9.])

In [68]:
# tensor to numpy array
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [69]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

In [70]:
# change the tensor, what happens to 'numpt_tensor'?
tensor = tensor + 1
tensor, numpy_tensor  # they don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...'

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

What the random seed does is flavor the randomness.

In [75]:
torch.rand(2, 3)  # two rows and three columns

tensor([[0.4177, 0.8038, 0.0186],
        [0.8043, 0.4429, 0.5728]])

In [76]:
torch.rand(3, 3)  # 3 rows and 3 columns, random numbers each time, but how to share

tensor([[0.0229, 0.2974, 0.8495],
        [0.7577, 0.6082, 0.9744],
        [0.9278, 0.9874, 0.3397]])

In [79]:
import torch
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1931, 0.9093, 0.2882, 0.4254],
        [0.3748, 0.5379, 0.3931, 0.2704],
        [0.6702, 0.3147, 0.9710, 0.0931]])
tensor([[0.2924, 0.4091, 0.9240, 0.7209],
        [0.5694, 0.0211, 0.0451, 0.8158],
        [0.3674, 0.5675, 0.3561, 0.0737]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
# make some random but reproducable tensors
import torch

# set the random seed
RANDOM_SEED = 42  # set to what ever you want
torch.manual_seed(RANDOM_SEED)  # need to set seed before creating each tensor
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resource for reproducability
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes tomake everything work

Easiest = Use Google Colab for a free GPU (options to upgrade as well)
* Use your own GPU - takes a bit of setup and requires purchasing a GPU, there's lot's of options.

* Use cloud computing, GCP, AWS, Azure, these services allow to rent a computer on the cloud and access them
* https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

For 2, 3, PyTorch + GPU drivers (CUDA) refer to PyTorch setting up
* https://pytorch.org/get-started/locally/




In [1]:
# 1. Getting the GPU
# change the runtime type
!nvidia-smi



Sat Apr 27 17:50:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# check gpu access with PyTorch
import torch

torch.cuda.is_available()


True

In [3]:
# setup device aganotic code
# use it if is available, set the device variable
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count the number of GPUs
torch.cuda.device_count()

1

### PyTorch Agnostic Code
* https://pytorch.org/docs/stable/notes/cuda.html

## Putting tensors and models in the GPU

The reason we want our models on the GPU is because using the GPU results in faster computations.



In [8]:
# Create a tensor (default is on the cpu)
tensor = torch.tensor([1, 2, 3], device="cpu") # 0 dimensions with 1 item 1 row and 3 columns
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [9]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### moving tensors back to the cpu


In [15]:
# if tensor is on gpu, can't transform it to numpy
# tensor_on_gpu.numpy()  # fails becaus numpy needs to on cpu
tensor_on_cpu = tensor.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [16]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')